### ISSUE TITLE
About the input file in polygenic

### ISSUE THREAD

**Issue by JielinLi** [Narasimhan-Lab/1000-genomes-natural-selection#3]
Hello, I want to ask in 'polygenic.py', how i can get the 'ld' and 'B statistics' file? it's calculated from your own data or from the BBJ？

**Comment by mktle** [comment]
Hi, we actually ended up matching by recombination rate instead of LD, so I'll update the scripts. We used files from the following papers (after sorting by chromosome and position):

Recombination rate map: https://pubmed.ncbi.nlm.nih.gov/30679340/
Background selection values: https://pubmed.ncbi.nlm.nih.gov/19424416/, which eventually links to http://www.phrap.org/othersoftware.html

**Comment by JielinLi** [comment]
Okay, thank you very much for your response!

**Comment by JielinLi** [comment]
Hi, I got to the http://www.phrap.org/othersoftware.html and download the B statistics data from 'http://www.phrap.org/software_dir/mcvicker_dir/bkgd.tar.gz' and I found there are three columns after adding the 'chr' for the file. But in your code, the b_file has more than three columns, can you tell me what every column represents for?

**Comment by mktle** [comment]
Thanks for bringing this up! Each line in the B statistic file should have information for chr/pos, B statistic decile (i.e., a number from 0 to 9 that’s calculated from the McVicker file), and the ancestral/derived alleles.

To make it easier to use the script with different input files and understand what the code is doing,  I made some changes to `polygenic_config.yml` and `polygenic_window_test.py` (#6 ). Once you have your input files (recombination rate map, B statistic deciles, GWAS file, and selection scan file), you can edit their paths and column names in `polygenic_config.yml`. `polygenic_window_test.py` will then parse the files using those column names.

These changes have also been documented in the README. Let me know if you have any other questions or issues getting this set up!

**Comment by JielinLi** [comment]
Your modifications and explanations of the file are very clear. But I also have a question that if the 'anc' and 'der' alleles in the B-score file are matched with the hg19 after transforming the position from hg18 to hg19？Because I do this but found so many "NA" in my final B-score file.

**Comment by mktle** [comment]
Yes, the code [linked here](https://github.com/Narasimhan-Lab/1000-genomes-natural-selection/blob/783770280a33612773ad15fdb1cb7916dabc3af3/src/polygenic_scan/polygenic_window_test.py#L273-L276) checks for whether the derived/reference allele pair matches the alleles in the selection scan file. If the alleles are different, then the script moves on to the next position.

There is also a check ([code linked here](https://github.com/Narasimhan-Lab/1000-genomes-natural-selection/blob/783770280a33612773ad15fdb1cb7916dabc3af3/src/polygenic_scan/polygenic_window_test.py#L268-L271)) that will skip the current position if it was not found in the B statistic file.

**Comment by JielinLi** [comment]
Thank you so much!
Also, I want to know that the second column of origin B-score file is the "length of the segment in bp", but in your input file, it's position. 
For example, the beginning of the origin file is:
835 437756
830 89637
854 48461
when transform it to position, is it should be:
835 437756
830 572393
854 575854
which simply sum the length of the segment?

**Comment by mktle** [comment]
Yes, that's right! i.e., if you sum up the numbers in the second column, it will equal the number of bases for that chromosome in [NCBI36/hg18](https://www.ncbi.nlm.nih.gov/grc/human/data?asm=NCBI36). However, that does mean that if your other files use a different reference, you'll have to convert these positions to the other coordinate system so that `polygenic_window_test.py` can match the positions to your other files.

For example, for our study, we ported the McVicker files to GRCh37 chr/pos format and took the subset of positions that overlapped with the positions in our ancient DNA data (1240k capture array). We then computed the B value deciles.

**Comment by JielinLi** [comment]
Okey, I get it! Thank you so much!

**Comment by JielinLi** [comment]
Hello, I also want to identify that after taking the subset of positions, there are only about 3000 locus in the final B-score file, is it right?

**Comment by mktle** [comment]
Hi, there should be a lot more than 3000—which subset of the positions did you take?

**Comment by JielinLi** [comment]
I take the subset of 1240k positions from the B-score file after porting the 'pos' in the McVicker files using the 'liftover' and using the file 'hg18ToHg19.over.chain'', is it right?

**Comment by mktle** [comment]
Yes, that should be right. If you want, you could share more details about the commands/code you ran and I could try to help you troubleshoot.

**Comment by JielinLi** [comment]
Yes, thank you so much! 

Firstly, I sum up the length of the segment:
for (i in 1:22){
  chr=read.table(paste0("chr",i,".bkgd"))
  chr[,3]=NA
 for (j in 1:nrow(chr)){
  chr[j,3]=sum(chr[1:j,2])
 }
  chr[,4]=i
  if(i==1){
    newchr=chr
  }else{
  newchr=rbind(newchr,chr)
  }
}

Secondly, I used the 'liftover':
liftOver bscore.pos hg18ToHg19.over.chain.gz bscore19.pos unmapped

Thirdly, I took the subset of the '1240K' position file from the B-score file:
I combined the column of 'chr' and 'pos' of booth B-score file and 1240k file, and then found the same rows between them. 
a=read.table('bscore19.pos')
b=read.table('1240k.pos')
a[,4]=paste(a$chr,a$pos)
b[,5]=paste(b$chr,b$pos)
c=a[a[,4]==b[,5],]

**Comment by mktle** [comment]
I believe this is because you don't expand the ranges in the B-score file (i.e., a line with 830 89637 means that the next 89637 positions have that score, not just the base 89637 positions over). So if you don't expand them, the intersection will just have the endpoints that are explicitly listed in the file. Let me know if that makes sense, or I could write another script as an example.

**Comment by JielinLi** [comment]
Yes, you are right. Do you mean that for the first line '830 89637', position 1-89637 has the score of 830, and for the next line '854 48461', position 89638-138098 has the score of 854?

**Comment by mktle** [comment]
Yes, the first 89637 bases in the NCBI36/hg18 reference coordinates would have a score of 830

**Comment by JielinLi** [comment]
OK, thank you!

**Comment by mktle** [comment]
No problem! Let me know if you run into any more issues
